src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name_product = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0)]
    private ?string $quantity = null;

    #[ORM\Column]
    private ?bool $stock = null;

    #[ORM\Column(length: 255)]
    private ?string $short_description = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $long_description = null;

    /**
     * @var Collection<int, ImgProduit>
     */
    #[ORM\OneToMany(targetEntity: ImgProduit::class, mappedBy: 'produit')]
    private Collection $imgs;

    public function __construct()
    {
        $this->imgs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameProduct(): ?string
    {
        return $this->name_product;
    }

    public function setNameProduct(string $name_product): static
    {
        $this->name_product = $name_product;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->quantity;
    }

    public function setQuantity(string $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function isStock(): ?bool
    {
        return $this->stock;
    }

    public function setStock(bool $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): static
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->long_description;
    }

    public function setLongDescription(?string $long_description): static
    {
        $this->long_description = $long_description;

        return $this;
    }

    /**
     * @return Collection<int, ImgProduit>
     */
    public function getImgs(): Collection
    {
        return $this->imgs;
    }

    public function addImg(ImgProduit $img): static
    {
        if (!$this->imgs->contains($img)) {
            $this->imgs->add($img);
            $img->setProduit($this);
        }

        return $this;
    }

    public function removeImg(ImgProduit $img): static
    {
        if ($this->imgs->removeElement($img)) {
            // set the owning side to null (unless already changed)
            if ($img->getProduit() === $this) {
                $img->setProduit(null);
            }
        }

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('field_name')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Repository\ProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class ProduitController extends AbstractController
{   
    #[Route('/produit/{id}', name: "produit_item")]
    public function item(Produit $product): Response
    {
        // dd($article->getId()); 
        return $this->render('produit/unique.html.twig', [
        'produit' => $product
    ]);
    }
    #[Route('/produits', name: 'produits')]
    public function index(ProduitRepository $produitRepository): Response
    {   
        $produit = $produitRepository->findAll();
        // dd($produit);
        return $this->render('produit/index.html.twig', [
            'produit' => $produit,
            'controller_name' => 'Nos produits',
        ]);
    }
}

templates/produit/form.html.twig
  <div class="max-w-[300px] mx-auto">{{ form(productForm) }}</div>

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello products{% endblock %}

{% block header %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
{{ include('nav.html.twig') }}
{% endblock %}
{% block contenent %}


<div class="example-wrapper">


    <button><a href>/produit/{id}</a>
    </button>

    {% for products in produit %}
    <section class="">
    <div class="container">
        <div class="row border text-center">
            <h2>{{produit.nameProduct}}</h2>
            {# <div class="col-lg-6">
                <div class=" mb-4">
                A VENIR
                    <p>{{ produit.dateproduit|date('d/m/Y')}}</p>
                </div>
            </div> #}
            <div class="col-lg-6">
                <div class=" mb-4">
                    <h4>{{produit.Price}}</h4>
                </div>
            </div>
            <div class="col-lg-6">
                <div class=" mb-4">
                    <h4>{{produit.Quantity}}</h4>
                </div>
            </div>
            <div class="col-lg-6">
                <div class=" mb-4">
                    <h4>{{produit.Stock}}</h4>
                </div>
            </div>
            <div class="col-lg-6">
                <div class=" mb-4">
                    <p>{{produit.shortDescription}}</p>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="mb-4">
                    {# <p>{{produit.longDescription}}</p> #}
                    {# <p> {{categorieProduit.name}}</p> #}
                </div>
            </div>
            <a class="btn btn-primary" href="{{path("produit_item", {id: produits.id})}}">
            Lire...
            </a>
        </div>
    </div>
</section>
<br>
    {% endfor %}
</div>
{% endblock %}

templates/produit/unique.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DisplayProduct{% endblock %}

{% block contenent %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>
{{ include('nav.html.twig') }}
<section class="">
    <div class="container">
        <div class="row border text-center">
            <h2>{{produit.nameProduct}}</h2>
            <div class="col-lg-12">
                <div class=" mb-4">
                    <h4>{{produit.Price}}</h4>
                </div>
            </div>  
            <div class="col-lg-12">
                <div class=" mb-4">
                   <h4>{{produit.Quantity}}</h4>
                </div>
            </div> 
            <div class="col-lg-12">
                <div class=" mb-4">
                   <h4>{{produit.Stock}}</h4>
                </div>
            </div>          
            
            <div class="col-lg-12">
                <div class=" mb-4">
                    <p>Description :  <br>{{produit.shortDescription}}</p>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="mb-4">
                    <p>Texte : <br>{{article.textArticle}}</p>
                    {% for categories in article %}
                    <p><br>{{article.categories}}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="col-lg-12">
            {% if (produit.id is empty)%}
            <a class="col-lg-3 mb-4 btn btn-primary" href="{{path("article_item", {id: article.id -1})}}">
            "Précédent"
            </a>
            {% endif %}
            {% if (produit.id is empty)%}
            <a class="col-lg-3 mb-4 btn btn-primary" href="{{path("article_item", {id: article.id +1})}}">
            "Suivant"
            </a>
            {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock %}